Improve lexer/parser error messages
Lexer error messages:

jmespath.compile('fooasdfasdfasdfasdf.\"bar')"
jmespath.lexer.LexerError: Bad jmespath expression: Bad token '"bar': starting quote is missing the ending quote:
fooasdfasdfasdfasdf."bar
                    ^

Parser error messages:

jmespath.compile('foo]baz')"
jmespath.parser.ParseError: Invalid jmespath expression: Parse error at column 3 near token "]" (RBRACKET) for expression:
"foo]baz"
    ^